BEGIN;

TRUNCATE TABLE street_names RESTART IDENTITY;

INSERT INTO street_names (locale, value, freq_weight) VALUES
    ('en_US', 'Main', 100), ('en_US', 'Oak', 80), ('en_US', 'Maple', 75),
    ('en_US', 'Pine', 70), ('en_US', 'Cedar', 60), ('en_US', 'Elm', 60),
    ('en_US', 'Washington', 90), ('en_US', 'Lincoln', 70), ('en_US', 'Jefferson', 50),
    ('en_US', 'Madison', 50), ('en_US', 'Park', 85), ('en_US', 'Lake', 60),
    ('en_US', 'River', 50), ('en_US', 'Hill', 55), ('en_US', 'Ridge', 40),
    ('en_US', 'Meadow', 35), ('en_US', 'Forest', 30), ('en_US', 'Spring', 40),
    ('en_US', 'Sunset', 45), ('en_US', 'Sunrise', 30), ('en_US', 'First', 60),
    ('en_US', 'Second', 55), ('en_US', 'Third', 50), ('en_US', 'Fourth', 40),
    ('en_US', 'Fifth', 35), ('en_US', 'Church', 65), ('en_US', 'School', 50),
    ('en_US', 'Market', 55), ('en_US', 'Mill', 40), ('en_US', 'Broadway', 35),
    ('en_US', 'North', 50), ('en_US', 'South', 50), ('en_US', 'East', 45),
    ('en_US', 'West', 45), ('en_US', 'Highland', 40), ('en_US', 'Walnut', 45),
    ('en_US', 'Birch', 35), ('en_US', 'Cherry', 45), ('en_US', 'Chestnut', 35),
    ('en_US', 'Willow', 40), ('en_US', 'Adams', 30), ('en_US', 'Jackson', 40),
    ('en_US', 'Franklin', 40), ('en_US', 'Roosevelt', 25), ('en_US', 'Kennedy', 25),
    ('en_US', 'Liberty', 30), ('en_US', 'Union', 35), ('en_US', 'Center', 40),
    ('en_US', 'Central', 35), ('en_US', 'Valley', 35), ('en_US', 'Hickory', 25),
    ('en_US', 'Magnolia', 25), ('en_US', 'Dogwood', 20), ('en_US', 'Sycamore', 25),
    ('en_US', 'Poplar', 25), ('en_US', 'Aspen', 20), ('en_US', 'Juniper', 15),
    ('en_US', 'Laurel', 20), ('en_US', 'Holly', 20), ('en_US', 'Ivy', 15),
    ('en_US', 'Rose', 30), ('en_US', 'Lily', 20), ('en_US', 'Violet', 15),
    ('en_US', 'Garden', 25), ('en_US', 'Orchard', 20), ('en_US', 'Grove', 25),
    ('en_US', 'Brook', 25), ('en_US', 'Creek', 30), ('en_US', 'Bay', 25),
    ('en_US', 'Beach', 25), ('en_US', 'Harbor', 20), ('en_US', 'Island', 20),
    ('en_US', 'Ocean', 20), ('en_US', 'Mountain', 25), ('en_US', 'Summit', 20),
    ('en_US', 'Prospect', 25), ('en_US', 'Pleasant', 25), ('en_US', 'Fair', 20),
    ('en_US', 'High', 30), ('en_US', 'Low', 15), ('en_US', 'Old', 25),
    ('en_US', 'New', 25), ('en_US', 'Green', 40), ('en_US', 'White', 30),
    ('en_US', 'Red', 25), ('en_US', 'Gold', 20), ('en_US', 'Silver', 20),
    ('en_US', 'Stone', 30), ('en_US', 'Brick', 20), ('en_US', 'Wood', 30),
    ('en_US', 'Glen', 20), ('en_US', 'Dale', 20), ('en_US', 'Heath', 15),
    ('en_US', 'Moore', 20), ('en_US', 'Taylor', 20), ('en_US', 'Harrison', 20),
    ('en_US', 'Wilson', 20), ('en_US', 'Monroe', 20), ('en_US', 'Garfield', 15),
    ('en_US', 'Grant', 20), ('en_US', 'Sherman', 15), ('en_US', 'Pershing', 10);

INSERT INTO street_names (locale, value, freq_weight) VALUES
    ('de_DE', 'Haupt', 100), ('de_DE', 'Bahnhof', 95), ('de_DE', 'Schul', 80),
    ('de_DE', 'Kirch', 75), ('de_DE', 'Markt', 70), ('de_DE', 'Berg', 65),
    ('de_DE', 'Garten', 60), ('de_DE', 'Wald', 60), ('de_DE', 'See', 50),
    ('de_DE', 'Wiesen', 55), ('de_DE', 'Schiller', 55), ('de_DE', 'Goethe', 55),
    ('de_DE', 'Mozart', 45), ('de_DE', 'Beethoven', 45), ('de_DE', 'Bach', 50),
    ('de_DE', 'Kant', 35), ('de_DE', 'Luther', 40), ('de_DE', 'Bismarck', 35),
    ('de_DE', 'Berliner', 50), ('de_DE', 'Hamburger', 40), ('de_DE', 'Münchner', 35),
    ('de_DE', 'Kölner', 35), ('de_DE', 'Frankfurter', 40), ('de_DE', 'Dresdner', 30),
    ('de_DE', 'Linden', 60), ('de_DE', 'Eichen', 40), ('de_DE', 'Birken', 40),
    ('de_DE', 'Tannen', 35), ('de_DE', 'Buchen', 35), ('de_DE', 'Kastanien', 30),
    ('de_DE', 'Ahorn', 25), ('de_DE', 'Post', 45), ('de_DE', 'Neue', 40),
    ('de_DE', 'Alte', 40), ('de_DE', 'Lange', 35), ('de_DE', 'Kurze', 25),
    ('de_DE', 'Breite', 30), ('de_DE', 'Hohe', 25), ('de_DE', 'Friedrich', 55),
    ('de_DE', 'Wilhelm', 55), ('de_DE', 'Karl', 55), ('de_DE', 'Ludwig', 45),
    ('de_DE', 'Otto', 40), ('de_DE', 'Heinrich', 40), ('de_DE', 'Mühl', 50),
    ('de_DE', 'Stein', 45), ('de_DE', 'Feld', 45), ('de_DE', 'Dorf', 50),
    ('de_DE', 'Stadt', 45), ('de_DE', 'Schloss', 35), ('de_DE', 'Burg', 35),
    ('de_DE', 'Turm', 25), ('de_DE', 'Brücken', 30), ('de_DE', 'Kanal', 25),
    ('de_DE', 'Hafen', 25), ('de_DE', 'Industrie', 20), ('de_DE', 'Gewerbe', 20),
    ('de_DE', 'Sonnen', 40), ('de_DE', 'Mond', 25), ('de_DE', 'Stern', 30),
    ('de_DE', 'Morgen', 25), ('de_DE', 'Abend', 20), ('de_DE', 'Nord', 30),
    ('de_DE', 'Süd', 30), ('de_DE', 'Ost', 25), ('de_DE', 'West', 25),
    ('de_DE', 'Richard-Wagner', 20), ('de_DE', 'Albert-Einstein', 20),
    ('de_DE', 'Max-Planck', 20), ('de_DE', 'Konrad-Adenauer', 25),
    ('de_DE', 'Willy-Brandt', 25), ('de_DE', 'Helmut-Schmidt', 15),
    ('de_DE', 'Lessing', 25), ('de_DE', 'Herder', 25), ('de_DE', 'Thomas-Mann', 20),
    ('de_DE', 'Brecht', 20), ('de_DE', 'Rilke', 20), ('de_DE', 'Hesse', 20),
    ('de_DE', 'Humboldt', 25), ('de_DE', 'Leibniz', 20), ('de_DE', 'Gauss', 15),
    ('de_DE', 'Röntgen', 15), ('de_DE', 'Siemens', 20), ('de_DE', 'Krupp', 15),
    ('de_DE', 'Gutenberg', 20), ('de_DE', 'Rhein', 30), ('de_DE', 'Donau', 30),
    ('de_DE', 'Main', 25), ('de_DE', 'Elb', 25), ('de_DE', 'Isar', 20),
    ('de_DE', 'Neckar', 20), ('de_DE', 'Moseler', 15), ('de_DE', 'Bayer', 20),
    ('de_DE', 'Hessen', 15), ('de_DE', 'Sachsen', 20), ('de_DE', 'Preussen', 15),
    ('de_DE', 'Parks', 25), ('de_DE', 'Blumen', 30), ('de_DE', 'Rosen', 30),
    ('de_DE', 'Fichten', 25), ('de_DE', 'Pappeln', 20), ('de_DE', 'Erlen', 20),
    ('de_DE', 'Flieder', 20), ('de_DE', 'Jasmin', 15), ('de_DE', 'Magnolien', 15);

COMMIT;